name = "philstubs"
version = "0.1.0"
target = "erlang"

description = "People Hardly Inspect Legislation - Searchable Templates Used Before anyone readS"
licences = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.0.0 and < 4.0.0"
gleam_json = ">= 1.0.0 and < 3.0.0"
lustre = ">= 4.0.0 and < 5.0.0"
wisp = ">= 0.14.0 and < 1.0.0"
mist = ">= 1.0.0 and < 2.0.0"
sqlight = ">= 0.8.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
